CREATE CONSTRAINT nutrient_id IF NOT EXISTS
FOR (n:Nutrient) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT additive_id IF NOT EXISTS
FOR (n:Additive) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT category_id IF NOT EXISTS
FOR (n:FoodCategory) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT allergen_id IF NOT EXISTS
FOR (n:Allergen) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT functional_class_id IF NOT EXISTS
FOR (n:FunctionalClass) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT health_outcome_id IF NOT EXISTS
FOR (n:HealthOutcome) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT health_claim_id IF NOT EXISTS
FOR (n:HealthClaim) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT source_id IF NOT EXISTS
FOR (n:Source) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT regulation_id IF NOT EXISTS
FOR (n:Regulation) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT alias_id IF NOT EXISTS
FOR (n:Alias) REQUIRE n.id IS UNIQUE;
